[build]
    command = "npm run build"
[dev]
  publish = "_site"
  [dev.https]
    certFile = "local/localhost.pem"
    keyFile = "local/localhost-key.pem"
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = """
      max-age=0,
      no-cache,
      no-store,
      must-revalidate
    """
    strict-transport-security = """
      max-age=31536000
    """
