[build]
    command = "npm run build"
[dev]
  publish = "_site"
  [dev.https]
    certFile = "local/localhost.pem"
    keyFile = "local/localhost-key.pem"
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = """
      max-age=0,
      no-cache,
      no-store,
      must-revalidate
    """
    strict-transport-security = """
      max-age=31536000
    """
    Content-Security-Policy = "default-src 'self'; script-src 'report-sample' 'self' https://plausible.io/js/script.manual.js; style-src 'report-sample' 'self' https://fonts.googleapis.com; object-src 'none'; base-uri 'self'; connect-src 'self' https://plausible.io; font-src 'self' https://fonts.gstatic.com; frame-src 'self'; img-src 'self'; manifest-src 'self'; media-src 'self'; worker-src 'none';"
