#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1 || {
    echo "==> Installing Homebrew dependencies..."
    brew bundle install --verbose --no-lock
  }
fi

if command -v rbenv >/dev/null 2>&1; then
  eval "$(rbenv init -)"

  if [ -z "$(rbenv version-name 2>/dev/null)" ]; then
    echo "==> Installing Ruby..."
    rbenv install --skip-existing
    rbenv rehash
  fi
fi

if command -v nodenv >/dev/null 2>&1; then
  eval "$(nodenv init -)"

  if [ -z "$(nodenv version-name 2>/dev/null)" ]; then
    echo "==> Installing Node..."
    nodenv install --skip-existing
    nodenv rehash
  fi
fi

if ! command -v bundle >/dev/null 2>&1; then
  echo "==> Installing Bundler..."
  gem install bundler

  if command -v rbenv >/dev/null 2>&1; then
    rbenv rehash
  fi
fi

if ! bundle check >/dev/null 2>&1; then
  echo "==> Installing Ruby dependencies..."
  bundle install
fi

echo "==> Installing Node dependencies..."
npm install

echo "==> Fetching latest style versions..."
mkdir -p tmp/

echo "==> Fetching proselint..."
curl -o tmp/proselint.zip -L https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip
rm -r _styles/proselint/ || true
unzip tmp/proselint.zip -d _styles/
rm tmp/proselint.zip

echo "==> Fetching write-good..."
curl -o tmp/write-good.zip -L https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
rm -r _styles/write-good/ || true
unzip tmp/write-good.zip -d _styles/
rm tmp/write-good.zip
