#!/bin/sh

# script/fix: Run automated format fixers

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Linting in fixer mode..."

if [ -n "$CI" ]; then
  set +e

  npm run format:fix
  npm run lint:js:fix
  npm run lint:ruby:fix
  npm run lint:shell

  set -e
fi
