#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

script/build

echo "==> Starting the server..."
bundle exec foreman start
