#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

echo "==> Removing cached Node dependencies..."
rm -rf node_modules

echo "==> Removing build artefacts..."
rm -rf _site
rm -rf .jekyll-cache
rm -rf dist

script/bootstrap
