#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

echo "==> Linting..."
if [ -n "$CI" ]; then
  set +e

  npm run format:fix
  FORMAT_SUCCESS=$?

  npm run lint:js:fix
  JS_SUCCESS=$?

  npm run lint:ruby:fix
  RUBY_SUCCESS=$?

  npm run lint:shell
  SHELL_SUCCESS=$?

  set -e

  [ $FORMAT_SUCCESS = "0" ]
  [ $JS_SUCCESS = "0" ]
  [ $RUBY_SUCCESS = "0" ]
  [ $SHELL_SUCCESS = "0" ]

  git diff-index HEAD
else
  npm run lint
fi

echo "==> Checking for required frontmatter..."
bundle exec jekyll test

echo "==> Testing..."
npm test
